import React from "react";
import { useEffect, useState } from "react";
import RainASMR from "../Sounds/rain.mp3";
import OceanASMR from "../Sounds/Ocean.mp3";
import whiteNoiseASMR from "../Sounds/whiteNoise.mp3";
import waves from "../images/waves.png";
import youtube from "../images/youtube.png";
import WhiteNoise from "../images/whiteNoise.png";
import { motion } from "framer-motion";
import { BsCloudRainFill, BsSoundwave } from "react-icons/bs";
import { TbBeach } from "react-icons/tb";
